language: c

before_install:
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -qq

install:
    - sudo apt-get install gcc-arm-none-eabi=4.9.3.2015q3-1trusty1

script:
  - make release
